package com.wwwescape.pixelinfo.ui.theme

import androidx.compose.ui.graphics.Color

// Light color scheme from DESIGN.md — the app's static (non-dynamic-color) light palette.
val Surface = Color(0xFFFDF8FD)
val SurfaceDim = Color(0xFFDDD9DE)
val SurfaceBright = Color(0xFFFDF8FD)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF7F2F8)
val SurfaceContainer = Color(0xFFF1ECF2)
val SurfaceContainerHigh = Color(0xFFEBE7EC)
val SurfaceContainerHighest = Color(0xFFE5E1E7)
val OnSurface = Color(0xFF1C1B1F)
val OnSurfaceVariant = Color(0xFF494551)
val InverseSurface = Color(0xFF313034)
val InverseOnSurface = Color(0xFFF4EFF5)
val Outline = Color(0xFF7A7582)
val OutlineVariant = Color(0xFFCBC4D2)
val SurfaceTint = Color(0xFF6750A4)
val Primary = Color(0xFF4F378A)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF6750A4)
val OnPrimaryContainer = Color(0xFFE0D2FF)
val InversePrimary = Color(0xFFCFBCFF)
val Secondary = Color(0xFF625B71)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFE8DEF9)
val OnSecondaryContainer = Color(0xFF686177)
val Tertiary = Color(0xFF633B48)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF7D5260)
val OnTertiaryContainer = Color(0xFFFFCBDA)
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)
val PrimaryFixed = Color(0xFFE9DDFF)
val PrimaryFixedDim = Color(0xFFCFBCFF)
val OnPrimaryFixed = Color(0xFF22005D)
val OnPrimaryFixedVariant = Color(0xFF4F378A)
val SecondaryFixed = Color(0xFFE8DEF9)
val SecondaryFixedDim = Color(0xFFCCC2DC)
val OnSecondaryFixed = Color(0xFF1E192B)
val OnSecondaryFixedVariant = Color(0xFF4A4358)
val TertiaryFixed = Color(0xFFFFD9E3)
val TertiaryFixedDim = Color(0xFFEEB8C8)
val OnTertiaryFixed = Color(0xFF31111D)
val OnTertiaryFixedVariant = Color(0xFF633B48)
val Background = Color(0xFFFDF8FD)
val OnBackground = Color(0xFF1C1B1F)
val SurfaceVariant = Color(0xFFE5E1E7)

// Dark color scheme from DESIGN_dark.md — the app's static dark palette. The "fixed" roles
// (PrimaryFixed, SecondaryFixed, TertiaryFixed and their dim/on variants, above) are identical
// between light and dark by M3 design, so they're shared rather than duplicated here.
val DarkSurface = Color(0xFF141317)
val DarkSurfaceDim = Color(0xFF141317)
val DarkSurfaceBright = Color(0xFF3A383D)
val DarkSurfaceContainerLowest = Color(0xFF0E0E11)
val DarkSurfaceContainerLow = Color(0xFF1C1B1F)
val DarkSurfaceContainer = Color(0xFF201F23)
val DarkSurfaceContainerHigh = Color(0xFF2B292D)
val DarkSurfaceContainerHighest = Color(0xFF353438)
val DarkOnSurface = Color(0xFFE5E1E7)
val DarkOnSurfaceVariant = Color(0xFFCBC4D2)
val DarkInverseSurface = Color(0xFFE5E1E7)
val DarkInverseOnSurface = Color(0xFF313034)
val DarkOutline = Color(0xFF948E9C)
val DarkOutlineVariant = Color(0xFF494551)
val DarkSurfaceTint = Color(0xFFCFBCFF)
val DarkPrimary = Color(0xFFCFBCFF)
val DarkOnPrimary = Color(0xFF381E72)
val DarkPrimaryContainer = Color(0xFF6750A4)
val DarkOnPrimaryContainer = Color(0xFFE0D2FF)
val DarkInversePrimary = Color(0xFF6750A4)
val DarkSecondary = Color(0xFFCCC2DC)
val DarkOnSecondary = Color(0xFF332D41)
val DarkSecondaryContainer = Color(0xFF4A4358)
val DarkOnSecondaryContainer = Color(0xFFBAB1CA)
val DarkTertiary = Color(0xFFEEB8C8)
val DarkOnTertiary = Color(0xFF492532)
val DarkTertiaryContainer = Color(0xFF7D5260)
val DarkOnTertiaryContainer = Color(0xFFFFCBDA)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF141317)
val DarkOnBackground = Color(0xFFE5E1E7)
val DarkSurfaceVariant = Color(0xFF353438)
